apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../stacks/kubernetes

configMapGenerator:
  - name: pipeline-install-config
    behavior: replace
    envs:
      - ./dev.params.env
  - name: pipeline-upstream-install-config
    behavior: merge
    envs:
      - ./dev.params.env

generators:
  - ./secretGenerator.yaml
