apiVersion: v1
kind: Secret
metadata:
  name: metadata-db-secrets
  annotations:
    kustomize.config.k8s.io/behavior: replace
stringData:
  MYSQL_PASSWORD: ENC[AES256_GCM,data:bbmalwDTDOC9I+8VCKRpJrGt,iv:wmN6cACjSzeWVSp+vzRI5/n0WYPpt499boC2Z+e6gR4=,tag:UUIFqVF/OQp6xsOs/kFTtA==,type:str]
  MYSQL_USERNAME: ENC[AES256_GCM,data:gtoLudU=,iv:D1Z11wBVps8UPMA8mRq5sfq2TmsHP23w2Eiya/Juq54=,tag:q+N2kfFdIJWH1aVAesEY7A==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:306688209471:key/12508297-ebc0-4462-9d7b-b9dd4194fbb2
      created_at: "2020-09-17T13:35:42Z"
      enc: AQICAHjTbzZgAG3/nImp5TZ58QNm0ZbGAFtYGp7gNf51MIT9owHPkphmyDbgDV6f8NQ8WdJjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVfV7yJ6XaYlVdY8MAgEQgDs/KqpSxp4Ig+0tnogllN6c7c6wFlIMMBI+gVkJ7GMOiWQ0C76ByKbBabUmkNJTzGUqyu9kL2xK5N52Cw==
      aws_profile: ""
    - arn: arn:aws:kms:eu-west-1:306688209471:key/e598e7cf-7ad2-414a-ac14-682799b01cf3
      created_at: "2020-09-17T13:35:42Z"
      enc: AQICAHg471beSeDHcB9UzbiLSOgQlLig6z9sgOr3/sa4YPh/pQEk/ADYdBCP14tOMRsmZqJ/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMxGRWztLr9vETYlzfAgEQgDtO37TEOsbRH5LAw7NIbxIUrnO5o+S0UkWZvwi2QR8qw7LxusGRFpWN5Kaqq5HSC3H48FlZqBAo7L9RTw==
      aws_profile: ""
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: "2020-09-17T13:35:43Z"
  mac: ENC[AES256_GCM,data:HCpV/NbRqQzVJe/xuo9plMXce7nAUDTZoIwCSaMnvonC7uePjoht+glZqF51r1BMpqUMMY7d7ZCjIzpjpQKcjY6HmZxjT2n8e24Agt6P1C1Hpw37gIkFzwNH0Nq/YiKa06pODjXWaJxSkYDTS52FScMTWla8CZpeQdq+ahedKDE=,iv:WBgqMLTYeMl0vVFg6aiHjUOwjtRkKcT2GCEtkhogf0Q=,tag:43qLXSVA2EkouV6TBN1r5g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.6.1
